[build]
command = "npm run docsite build"
publish = "docsite-build"

[[redirects]]
  from = "/"
  to = "https://docs.openzeppelin.com/contracts"
  status = 301
  force = true

[[redirects]]
  from = "/v2.3.0/*"
  to = "https://docs.openzeppelin.com/contracts/2.x/:splat"
  status = 301
  force = true
